trigger:
- main  # or your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'  # from when you connected SonarCloud
    organization: 'swatisinha8403'  # found in your SonarCloud URL
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'swatisinha8403_Pipeline'
    cliProjectName: 'Pipeline'

- script: |
    echo "Your build commands go here"
    npm install
    npm run build
  displayName: 'Build Project'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
